config/routes.rb
Rails.application.routes.draw do
  root 'items#top'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  
  resources :users, only: [:index] do
    collection do
      get 'logout'
    end 
  end
  resources :credit_cards, only: [:index, :new, :create, :show, :destroy]

  resources :purchase, only:[:index] do
    collection do
      get 'done', to: 'purchase#done'
    end
    member do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
    end
  end
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search', to: 'items#search'
    end
  end

  resources :categories, only: :show
  resources :images, only: [:index, :new, :show]
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  validates :user_id, :name, :description, :price, :condition_id, :wait, :postage, :category_id, :brand_id, :prefecture_id, presence: true
  validates :images, presence: true
  validates :price, :numericality => { :greater_than => 299 }
  validates :price, :numericality => { :less_than => 9999999 }
  
  belongs_to :user, optional: true
  has_many :comments
  belongs_to :category
  belongs_to :brand

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  belongs_to_active_hash :prefecture
  belongs_to_active_hash :condition
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_search
  before_action :set_item, only: [:show, :update, :edit, :destroy]

  def index
    @items = Item.order('created_at DESC').limit(8)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: "出品しました"
    else
      redirect_to new_item_path, alert: "出品できません。入力必須項目を確認してください"
    end
  end

  def new
    @item = Item.new
    @item.images.new
    @category_parent_array = []
    @category = Category.roots.each do |parent|
    @category_parent_array << parent.name
    end
  end

  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find(params[:parent_id]).children
  end

  def top
    @items = Item.includes(:images).order('created_at DESC').limit(4)
    @items_category = Item.where(category_id: [1...200]).includes(:images).order('created_at DESC').limit(3)
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  def search
    @search = Item.ransack(params[:q])
    @items = @search.result.order("id DESC").page(params[:page]).per(5)
  end
  
  def edit
  end


  def show

  end

  def update  #事前に商品情報更新用アクションを定義
    if @item.update(item_params)
      redirect_to item_path, notice: "更新しました。"
    else
      redirect_to edit_item_path, alert: "変更できません。入力必須項目を確認してください。"
    end
  end

  def destroy
    if @item.destroy
      redirect_to '/'
    else
      render :show
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :category_id, :brand_id, :price, :condition_id, :wait, :postage, :prefecture_id, :buyer_id, :shipping_fee, :shipping_day, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_category.html.haml
= link_to item_path(item.id) do
  .i__middle__container__border
    .i__middle__container__border__content
      .i__middle__container__border__content__image
        = image_tag item.images[0].src.to_s, width: '200px'
        -if item.buyer_id.present?
          .i__middle__container__border__content__image--triangle
          .i__middle__container__border__content__image__soldout
            SOLD
      .i__middle__container__border__content__info
        .i__middle__container__border__content__info__name
          = item.name
        .i__middle__container__border__content__info__price
          ¥
          = item.price
          =icon('far','heart') do
            %span 100

app/views/items/_item.html.haml
= link_to item_path(item.id) do
  .i__middle__container__border
    .i__middle__container__border__content
      .i__middle__container__border__content__image
        %span.i__middle__container__border__content__image__price
          ¥
          = item.price
        = image_tag item.images[0].src.to_s, width: '200px'
        -if item.buyer_id.present?
          .i__middle__container__border__content__image--triangle
          .i__middle__container__border__content__image__soldout
            SOLD
      .i__middle__container__border__content__info
        .i__middle__container__border__content__info__name
          = item.name
          .i__middle__container__border__content__info__name__icon
            =icon('far','heart') do
              %span 100

app/views/items/edit.html.haml
.r__container
  .r__logo
    = link_to image_tag('logo.png', width: '170', height: '60'), root_path

  .r__form__container
    = form_with model: @item, local: true do |f|
      %ul
        .r__title__container
          %p.message-title 商品の情報を入力
        .r__image__container
          %p.message 商品出品画像（必須）
          %p.message 最大5枚までアップロード出来ます
          .post__drop__box__container
            .prev-content
              - @item.images.each do |image|
                .preview-box
                  .upper-box
                    = image_tag image.src.url, alt: "preview"
                  .lower-box
                    .delete-box
                      .delete-btn
                        %span 削除
            .label-content
              %label{for: "item_images_attributes_0_src", class: "label-box", id: "label-box--0"}
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              = f.fields_for :images do |i|
                = i.file_field :src, class: "hidden-field"
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][1][src]", id: "item_images_attributes_1_src" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][2][src]", id: "item_images_attributes_2_src" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][3][src]", id: "item_images_attributes_3_src" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][4][src]", id: "item_images_attributes_4_src" }
                = i.check_box :_destroy, class: "hidden-checkbox"
        .r__item__container
          %p.message 商品名（必須）
          = f.text_field :name, class: "name-box",  placeholder: "商品名（必須 40文字まで)"
          %p.message 商品の説明（必須）
          = f.text_area :description, class: "description-box", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）おじいちゃんの形見です。", rows: "5"
        .r__details__container
          %p.message 商品の詳細
          %p.message カテゴリー（必須）
          .sell-category-box
            = f.collection_select :category_id, @category_parent_array, :id, :name, {prompt: "---"}, {class: 'sell__item-category', id: 'parent_category'}
          %p.message ブランド名（任意）
          = f.collection_select :brand_id, Brand.all, :id, :name, {prompt: "選択してください"}, {class: "select-box"}
          %p.message 商品の状態（必須）
          = f.collection_select :condition_id, Condition.all, :id, :name, {prompt: "選択してください"}, {class: "select-box"}
        .r__post__container
          %p.message 配送について
          %p.message 配送料の負担（必須）
          = f.select :postage,[["送料込み(出品者負担)"], ["着払い（購入者負担）"]], {prompt: "選択してください"}, {class: "select-box"}
          %p.message 発送元の地域（必須）
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, {class: "select-box"}
          %p.message 発送までの日数（必須）
          = f.select :wait,[["1~2日で発送"], ["2~3日で発送"],["4~7日で発送"]], {prompt: "選択してください"},{class:"select-box"}
        .r__price__container
          %p.message 価格について（¥300〜9,999,999）
          .content-flex
            .message 価格（必須）
            .price
              %span ¥
              =f.number_field :price, placeholder: "0", type: "number", class:"price-box"
        .r__submit__container
          .button
            = f.submit "変更する", class: "exhibition"
          .back
            = link_to "キャンセル", item_path #仮置 本番は商品情報編集ページ遷移前のページに飛ぶ
        .r__attention__container
          %p.message 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

  .r__end__logo__container
    .r__end__logo__container__end__logo
      = link_to image_tag('logo.png', width: '170', height: '60'), root_path
      %p ©️FURIMA.inc

app/views/items/index.html.haml
= render 'layouts/header'

.i__main
  .i__main__items
    %h2.i__main__items__head 新着アイテム一覧
    .i__main__items__lists
      .i__main__items__lists__items
        = render @items

.i__banner
  .i__banner__visual
    .i__banner__visual__content
      %h2.i__banner__visual__content__top だれでも簡単、人生を変えるフリマアプリ
      %p.i__banner__visual__content__text 今すぐ無料ダウンロード！
    .i__banner__visual__logo
      .i__banner__visual__logo__app
        = link_to "http://apple.com/jp/" do
          = image_tag 'apple-icon.png', alt: '',height: '50px', width: '165px', class: 'apple'
      .i__banner__visual__logo__app
        = link_to "http://google.co.jp" do
          = image_tag 'google-play.png', alt: '', height: '50px', width: '165px',class: 'google'
.i__footer
  = render 'layouts/footer'

app/views/items/new.html.haml
.t__container
  .t__logo
    = link_to image_tag('logo.png', width: '170', height: '60'), root_path

  .t__form__container
    = form_with model: @item, local: true do |f|
      %ul
        .t__image__container
          %p.message 商品出品画像（必須）
          %p.message 最大5枚までアップロード出来ます
          .post__drop__box__container
            .prev-content
            .label-content
              %label{for: "item_images_attributes_0_src", class: "label-box", id: "label-box--0"}
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              = f.fields_for :images do |i|
                = i.file_field :src, class: "hidden-field"
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][1][src]", id: "item_images_attributes_1_src" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][2][src]", id: "item_images_attributes_2_src" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][3][src]", id: "item_images_attributes_3_src" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][4][src]", id: "item_images_attributes_4_src" }
        .t__item__container
          %p.message 商品名（必須）
          = f.text_field :name, class: "name-box",  placeholder: "商品名（必須 40文字まで)"
          %p.message 商品の説明（必須）
          = f.text_area :description, class: "description-box", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）", rows: "5"
        .t__details__container
          %p.message 商品の詳細
          %p.message カテゴリー（必須）
          .sell-category-box
            = f.collection_select :category_id, Category.roots, :id, :name, {prompt: "選択してください", selected: @item.category&.root_id}, {class: 'sell__item-category', id: 'parent_category'}
          %p.message ブランド名（任意）
          = f.collection_select :brand_id, Brand.all, :id, :name, {prompt: "選択してください"}, {class: "select-box"}
          %p.message 商品の状態（必須）
          = f.collection_select :condition_id, Condition.all, :id, :name, {prompt: "選択してください"}, {class: "select-box"}
        .t__post__container
          %p.message 配送について
          %p.message 配送料の負担（必須）
          = f.select :postage,[["送料込み(出品者負担)"], ["着払い（購入者負担）"]], {prompt: "選択してください"}, {class: "select-box"}
          %p.message 発送元の地域（必須）
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, {class: "select-box"}
          %p.message 発送までの日数（必須）
          = f.select :wait,[["1~2日で発送"], ["2~3日で発送"],["4~7日で発送"]], {prompt: "選択してください"},{class:"select-box"}
        .t__price__container
          %p.message 価格について（¥300〜9,999,999）
          .content-flex
            .message 価格（必須）
            .price
              %span ¥
              =f.number_field :price, placeholder: "0", type: "number", class:"price-box"
        .t__submit__container
          .button
            = f.submit "出品する", class: "exhibition"
          .back
            = link_to "もどる", root_path
        .t__attention__container
          %p.message 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

  .t__end__logo__container
    .t__end__logo__container__end__logo
      = link_to image_tag('logo.png', :width => '170', :height => '60'), root_path
      %p ©️FURIMA.inc 

app/views/items/search.html.haml
= render partial: 'layouts/header'

%main.y__l-container
  .y__l-container-box
    .y__search-result
      .y__search-result-header
        = @search.name_cont
        の検索結果
        .y__search-result-number
          1 - 
          = @items.count
          件の表示
        .y__search-result-items-box
          - @items.each do |item|
            .result__item
              =link_to item_path(item.id),method: :get do
                .result__item__image
                  = image_tag item.images[0].src.url, height: "160px", width: "160px"
                  %p
                    ¥
                    = item.price
                  %span 
                    = item.name 
        = paginate @items

= render partial: 'layouts/footer'

app/views/items/show.html.haml
.k-header
  = render partial: 'layouts/header'

.k__main
  .k__showMain
    .k__content
      .k__itemBox
        .k__itemBox__name
          = @item.name
        .k__itemBox__body
          %ul
            %li
              = image_tag @item.images[0].src.to_s, class:"firstImage", width:520
              -if @item.buyer_id.present?
                .triangle
                .sold
                  SOLD
              %ul
                - @item.images.each do |image|
                  %li
                    = image_tag image.src.to_s, :width => "75", :height => "75",class:"imageList"
        .k__itemBox__price
          ¥ 
          =@item.price
          .k__itemBox__price-detail
            %span (税込)
            %span 送料込み
        .k__itemDetail
          .noticeMsg
            = simple_format @item.description
        .k__table
          %table
            %tbody
              %tr
                %th 出品者
                %td
                  = @item.user.nickname
              %tr
                %th カテゴリー
                %td.k__table--blue
                  = link_to category_path(@item.category.id) do
                    =@item.category.name 
              %tr
                %th ブランド
                %td
                  =@item.brand.name
              %tr
                %th 商品のサイズ
                %td
                  =@item.size
              %tr
                %th 商品の状態
                %td
                  =@item.condition.name
              %tr
                %th 配送料の負担
                %td
                  = @item.postage
              %tr
                %th 発送元の地域
                %td
                  = @item.prefecture.name
              %tr
                %th 発送日の目安
                %td
                  =@item.wait
        .k__optonalArea
          %ul
            %li.k__optinalBtn.k__likeBtn              
              =icon('fa','star')
              お気に入り 0
          %ul.k__optional
            %li.k__optionalBtn
              =link_to "#" do
                =icon('fa','flag')
                不適切な商品の通報

      .k__itemChangeBox
        %ul.k__itemChangeBox__btnList
          -if @item.buyer_id.present?
            %li.k__itemChangeBox__btnList__soldOutNotice
              売り切れました
          - elsif user_signed_in? && current_user.id == @item.user_id
            .r__itemManageBox
              = link_to "編集", edit_item_path(@item), class: "r__itemManageBox__edit" 
              = link_to "削除", item_path(@item.id), method: :delete, class: "r__itemManageBox__delete" 
          - else
            .k__itemChangeBox
              %button.k__itemChangeBox__btnList__buyBtn
                = link_to "購入画面に進む", purchase_path(@item), class:"k__itemChangeBox__btnList__buyBtn__link"
    
      .k__commentBox
        .k__commentBox__list
          .k__commentBox__list__icon
            =icon('fa','user')
          .k__commentBox__list__content
            .k__commentBox__list__content__name
              バイヤーテスト
            .k__commentBox__list__content__message
              test
            .k__commentBox__list__content__date
              2020-06-09 12:00:00 +0900

        .form
          %input.k__comment{type: "text"}
          .k__noticeMsg
            %p
              相手のことを考え丁寧なコメントを心がけましょう。
              %br 不快な言葉遣いなどは利用制限や退会処分となることがあります。
          %br
          %input.k__commentBtn{type: "submit", value: "コメントする"}

.k-footer
  = render partial: 'layouts/footer'

app/views/items/top.html.haml
= render partial: 'layouts/header', locals: { header: @header }
.i__main
  .i__main__visual
    .i__main__visual__content
      %h2.i__main__visual__content__top 人生を変えるフリマアプリ
      %p.i__main__visual__content__text 
        FURIMAはだれでもかんたんに出品・購入できる 
        %br
        フリマアプリです
      .i__main__visual__content__logo
        .i__main__visual__content__logo__app
          = link_to "http://apple.com/jp/" do
            = image_tag 'apple-icon.png', alt: '',height: '50px', width: '165px', class: 'apple'
        .i__main__visual__content__logo__app
          = link_to "http://google.co.jp" do
            = image_tag 'google-play.png', alt: '', height: '50px', width: '165px',class: 'google'

  .i__main__introduction
    %h2.i__main__introduction__top FURIMAが選ばれる3つの理由
    %ul.i__main__introduction__lists
      %li.i__main__introduction__lists__list
        .i__main__introduction__lists__list__pic
          = image_tag 'pict-reason-01.jpg', alt: '' , width: '100%', class: ''
          %span.i__main__introduction__lists__list__pic__num 1
        %h3.i__main__introduction__lists__list__text
          %span.i__main__introduction__lists__list__text__left 3分
          %span.i__main__introduction__lists__list__text__right ですぐに出品
        %p.i__main__introduction__lists__list__subtext スマホで入力するだけで簡単に出品できる！
      %li.i__main__introduction__lists__list
        .i__main__introduction__lists__list__pic
          = image_tag 'pict-reason-02.jpg', alt: '' , width: '100%', class: ''
          %span.i__main__introduction__lists__list__pic__num 2
        %h3.i__main__introduction__lists__list__text
          %span.i__main__introduction__lists__list__text__left シンプル
          %span.i__main__introduction__lists__list__text__right で使いやすい
        %p.i__main__introduction__lists__list__subtext めんどくさい入力は必要なく、検索も購入もスムーズ！ 
      %li.i__main__introduction__lists__list
        .i__main__introduction__lists__list__pic
          = image_tag 'pict-reason-03.jpg', alt: '' , width: '100%', class: ''
          %span.i__main__introduction__lists__list__pic__num 3
        %h3.i__main__introduction__lists__list__text
          %span.i__main__introduction__lists__list__text__left 業界最安
          %span.i__main__introduction__lists__list__text__right の手数料
        %p.i__main__introduction__lists__list__subtext 最大3%でお得に出品&購入！


  .i__main__middle
    .i__main__middle__content
      %h2.i__main__middle__content__top 会員数日本一位
      %p.i__main__middle__content__text 
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        欲しかったあの商品に出会えるかもしれません。
      .i__main__middle__content__logo
        .i__main__middle__content__logo__app
          = link_to "http://apple.com/jp/" do
            = image_tag 'apple-icon.png', alt: '',height: '50px', width: '165px', class: 'apple'
        .i__main__middle__content__logo__app
          = link_to "http://apple.com/jp/" do
            = image_tag 'google-play.png', alt: '', height: '50px', width: '165px',class: 'google'


  .i__main__features
    %h2.i__main__features__head FURIMAの特徴
    %ul.i__main__features__lists
      %li.i__main__features__lists__list
        .i__main__features__lists__list__pic
          = image_tag 'icon-01.png', alt: '' , width: '100%', class: ''
        %h3.i__main__features__lists__list__text 簡単に売り買いできる
        %p.i__main__features__lists__list__subtext スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.i__main__features__lists__list
        .i__main__features__lists__list__pic
          = image_tag 'icon-03.png', alt: '' , width: '100%', class: ''
        %h3.i__main__features__lists__list__text 売上金は即日振込みに対応
        %p.i__main__features__lists__list__subtext 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %li.i__main__features__lists__list
        .i__main__features__lists__list__pic
          = image_tag 'icon-04.png', alt: '' , width: '100%', class: ''
        %h3.i__main__features__lists__list__text 様々な支払いに対応
        %p.i__main__features__lists__list__subtext お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  .i__main__items
    %h2.i__main__items__head ピックアップカテゴリー
    .i__main__items__lists
      .i__main__items__lists__head 新規投稿商品
      .i__main__items__lists__items
        = render @items
      .i__main__items__lists__more
        = link_to 'もっと見る>',items_path
    %h2.i__main__items__head ピックアップカテゴリー
    .i__main__items__lists
      .i__main__items__lists__head 文房具
      .i__main__items__lists__items
        = render @items_category
.i__banner
  .i__banner__visual
    .i__banner__visual__content
      %h2.i__banner__visual__content__top だれでも簡単、人生を変えるフリマアプリ
      %p.i__banner__visual__content__text 今すぐ無料ダウンロード！
    .i__banner__visual__logo
      .i__banner__visual__logo__app
        = link_to "http://apple.com/jp/" do
          = image_tag 'apple-icon.png', alt: '',height: '50px', width: '165px', class: 'apple'
      .i__banner__visual__logo__app
        = link_to "http://google.co.jp" do
          = image_tag 'google-play.png', alt: '', height: '50px', width: '165px',class: 'google'
.i__footer
  = render partial: 'layouts/footer'