config/routes.rb
Rails.application.routes.draw do
  root 'items#top'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  
  resources :users, only: [:index] do
    collection do
      get 'logout'
    end 
  end
  resources :credit_cards, only: [:index, :new, :create, :show, :destroy]

  resources :purchase, only:[:index] do
    collection do
      get 'done', to: 'purchase#done'
    end
    member do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
    end
  end
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search', to: 'items#search'
    end
  end

  resources :categories, only: :show
  resources :images, only: [:index, :new, :show]
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # アソシエーション
  belongs_to :user, optional: true
  belongs_to_active_hash :prefecture
  
  # バリデーション
  validates :family_name, :first_name , :family_name_kana, :first_name_kana, :city, :postal_code, :local, :block, presence: true

  # 文字の形式制限
  validates :family_name, :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/,
    message: "全角文字のみが使えます" }
  validates :family_name_kana, :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/,
    message: "全角カナのみが使えます" }

  # 文字数制限
  validates :postal_code, length: { is: 7 }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord

  has_ancestry
  has_many :items

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :ancestry, :id, presence: true
  has_ancestry
  has_many :items
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    {id: 1, name: '新品'}, {id: 2, name: 'とても良い'}, {id: 3, name: '普通'},
    {id: 4, name: '少しの汚れ、傷'}, {id: 5, name: 'かなり古い'}
  ]
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :src, ImageUploader
  belongs_to :item, optional: true
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  validates :user_id, :name, :description, :price, :condition_id, :wait, :postage, :category_id, :brand_id, :prefecture_id, presence: true
  validates :images, presence: true
  validates :price, :numericality => { :greater_than => 299 }
  validates :price, :numericality => { :less_than => 9999999 }
  
  belongs_to :user, optional: true
  has_many :comments
  belongs_to :category
  belongs_to :brand

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  belongs_to_active_hash :prefecture
  belongs_to_active_hash :condition
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :credit_card
  has_many :items
  has_one :address

  # バリデーション
  validates :nickname, :family_name, :first_name, :family_name_kana, :first_name_kana, :birth_date, :phone_number, :gender, presence: true

  # 文字の形式制限
  validates :family_name, :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/,
    message: "全角文字のみが使えます" }
  validates :family_name_kana,:first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/,
    message: "全角カナのみが使えます" }


end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
  end
  
  def new
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_search
  before_action :set_item, only: [:show, :update, :edit, :destroy]

  def index
    @items = Item.order('created_at DESC').limit(8)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: "出品しました"
    else
      redirect_to new_item_path, alert: "出品できません。入力必須項目を確認してください"
    end
  end

  def new
    @item = Item.new
    @item.images.new
    @category_parent_array = []
    @category = Category.roots.each do |parent|
    @category_parent_array << parent.name
    end
  end

  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find(params[:parent_id]).children
  end

  def top
    @items = Item.includes(:images).order('created_at DESC').limit(4)
    @items_category = Item.where(category_id: [1...200]).includes(:images).order('created_at DESC').limit(3)
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  def search
    @search = Item.ransack(params[:q])
    @items = @search.result.order("id DESC").page(params[:page]).per(5)
  end
  
  def edit
  end


  def show

  end

  def update  #事前に商品情報更新用アクションを定義
    if @item.update(item_params)
      redirect_to item_path, notice: "更新しました。"
    else
      redirect_to edit_item_path, alert: "変更できません。入力必須項目を確認してください。"
    end
  end

  def destroy
    if @item.destroy
      redirect_to '/'
    else
      render :show
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :category_id, :brand_id, :price, :condition_id, :wait, :postage, :prefecture_id, :buyer_id, :shipping_fee, :shipping_day, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user_params, only: [:show, :edit, :update]

  private
  
  def set_user_params
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_category.html.haml
.t__header__box__sub__left--category
  %i.fas.fa-bars.category__icon
    = link_to "#", class: "categoryBtn" do
      = "カテゴリーから探す"
  .visibleTree
    %ul.firstMenu__parents
      - @category_parent_array.each do |parent|
        %li.firstMenu__parents__parent
          = link_to "#{parent.name}", "/categories/#{parent.id}", class: "item-link" 
          %ul.secondMenu__children
            - parent.children.each do |child|
              %li.secondMenu__children__child
                = link_to "#{child.name}", "/categories/#{child.id}", class: "item-link" 
                %ul.thirdMenu__grandchildren
                  - child.children.each do |grandchildren|
                    %li.thirdMenu__grandchildren__grandchild
                      = link_to "#{grandchildren.name}", "/categories/#{grandchildren.id}", class: "item-link" 

app/views/layouts/_confirm.html.haml
= form_with url: pay_items_path do
  :plain
    %script.payjp-button{"data-key" => "pk_test_c149998bf90f07f7522802f0", :src => "https://checkout.pay.jp", :type => "text/javascript"}

app/views/layouts/_footer.html.haml
.i__footer
  .i__footer__contents
    .ul.i__footer__contents__list
      %h2.i__footer__contents__list__top FURIMAについて
      %li
        = link_to '会社概要（運営会社）', root_path, class: "i__footer__contents__list__top" 
      %li
        = link_to 'プライバシーポリシー', root_path, class: "i__footer__contents__list__top" 
      %li
        = link_to 'FURIMA利用規約', root_path, class: "i__footer__contents__list__top" 
      %li
        = link_to 'ポイントに関する特約', root_path, class: "i__footer__contents__list__top" 
    .ul.i__footer__contents__list
      %h2.i__footer__contents__list__top FURIMAを見る
      %li
        = link_to 'カテゴリー一覧', root_path, class: "i__footer__contents__list__top" 
      %li
        = link_to 'ブランド一覧', root_path, class: "i__footer__contents__list__top" 
    .ul.i__footer__contents__list
      %h2.i__footer__contents__list__top ヘルプ＆ガイド
      %li
        = link_to 'FURIMAガイド', root_path, class: "i__footer__contents__list__top" 
      %li
        = link_to 'FURIMAロゴ利用ガイドライン', root_path, class: "i__footer__contents__list__top"

      %li
        = link_to 'お知らせ', root_path, class: "i__footer__contents__list__top" 

  .i__footer__logo
    = link_to root_path do
      = image_tag 'logo-white.png', alt: '', height: '40px', width: '140px', class: 'footer__logo__icon'
  %p © FURIMA
  - if user_signed_in?
    %a(href="/items/new")
      .i__btn__icon
        %span.i__btn__icon__text 出品する
        = image_tag 'icon_camera.png', alt: '' , height: '55px', width: '55px', class: ''
  - else
    %a(href="/users/sign_in")
      .i__btn__icon
        %span.i__btn__icon__text ログインして出品する
        = image_tag 'icon_camera.png', alt: '' , height: '55px', width: '55px', class: ''

app/views/layouts/_header.html.haml
.i__header
  .i__header__inner
    .i__header__inner__main
      .i__header__inner__main__logo
        = link_to "/" do
          = image_tag 'logo.png', alt: '', height: '40px', width: '140px', class: 'img-logo'
      = search_form_for @search, url: search_items_path, class: 'i__header__inner__main__search', method: :get do |f|
        = f.search_field :name_cont, placeholder: "キーワードから探す", class: 'i__header__inner__main__search__box'
        = button_tag type: 'submit', class: 'i__header__inner__main__search__btn' do
          = image_tag 'icon-search 1.png', alt: '',height: '22px', width:'22px', type: 'submit', class: 'header__inner__main__search__btn__icon'
          
    .i__header__inner__nav
      %ul.i__header__inner__nav__left
        %li.i__header__inner__nav__left__first
          = render "layouts/category"
        %li.i__header__inner__nav__left__second ブランド
      %ul.i__header__inner__nav__right
        -if user_signed_in?
          = link_to users_path(current_user),id: "btn" do
            %li.i__header__inner__nav__right__login マイページ
          = link_to destroy_user_session_path, method: :delete, id: "btn" do
            %li.i__header__inner__nav__right__login ログアウト
        -else
          = link_to new_user_session_path,id: "btn" do
            %li.i__header__inner__nav__right__login ログイン
          = link_to new_user_registration_path,id: "btn" do
            %li.i__header__inner__nav__right__login 新規会員登録

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FleamarketSample76a
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/mypage/_main.html.haml
.y__l-content
  %section.y__mypage-user-icon
    = link_to "" , class: "y__mypage-detail" do
      %figure
        = image_tag 'member_photo_noimage_thumb.png', alt: '', height: '60', width: '60', class: 'y__user-no-img'
      %h2.y__bold
        = current_user.nickname
      .y__mypage-number
        %div
          評価
          %span.y__bold
            0
        %div
          出品数
          %span.y__bold
            0

  %section.y__mypage-tab-container-notification-todo
    %ul.y__mypage-tabs
      %li.y__active
        = link_to 'お知らせ' , href: "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3466462615", alt: "mercari", width: "80", height:"65", data: {toggle: "tab"}
      %li
        = link_to 'やることリスト' , href: "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3466462615", alt: "mercari", width: "80", height:"65", data: {toggle: "tab"} 
    .y__tab-content
      .y__tab-content-img
      %ul#y__mypage-tab-notification.y__mypage-itemlist
        %li.y__mypage-item-not-found.y__bold お知らせの商品はありません
  -#  %ul#mypage-tab-todo.mypage-itemlist
  -#    %li.mypage-item-not-found.y__bold 現在やることリストはありません
  
  %section.y__mypage-tab-container
    %h2.y__mypage-tab-head
      購入した商品
    %ul.y__mypage-tabs
      %li.y__active
        = link_to '取引中' ,href: "#mypage-tab-transaction-now", data: {toggle: "tab"}
      %li
        = link_to '過去の取引' ,href: "#mypage-tab-transaction-old", data: {toggle: "tab"}
    .y__tab-content
      .y__tab-content-img
      %ul#y__mypage-tab-transaction-now.y__mypage-item-list
        %li.y__mypage-item-not-found.y__bold 取引中の商品がありません
    -#  %ul#mypage-tab-transaction-old.mypage-itemlist
    -#    %li.mypage-item-not-found.y__bold 過去に取引した商品はありません

app/views/mypage/_side.html.haml
.y__l-side
  %nav.y__mypage-nav
  %ul.y__mypage-nav-list
    = link_to users_path do
      %li.y__mypage-nav-list-item
        マイページ
        %i.fa.fa-angle-right
    = link_to "" do
      %li.y__mypage-nav-list-item
        お知らせ
        %i.fa.fa-angle-right
    = link_to "" do
      %li.y__mypage-nav-list-item
        やることリスト
        %i.fa.fa-angle-right
    = link_to "" do
      %li.y__mypage-nav-list-item
        いいね一覧
        %i.fa.fa-angle-right
    = link_to new_item_path do
      %li.y__mypage-nav-list-item
        出品する
        %i.fa.fa-angle-right
    = link_to "" do
      %li.y__mypage-nav-list-item
        下書き一覧
        %i.fa.fa-angle-right
    = link_to "" do
      %li.y__mypage-nav-list-item
        出品した商品-出品中
        %i.fa.fa-angle-right
    = link_to "" do
      %li.y__mypage-nav-list-item
        出品した商品-取引中
        %i.fa.fa-angle-right
    = link_to "" do
      %li.y__mypage-nav-list-item
        出品した商品-売却済
        %i.fa.fa-angle-right
    = link_to "" do
      %li.y__mypage-nav-list-item
        購入した商品-取引中
        %i.fa.fa-angle-right
    = link_to "" do
      %li.y__mypage-nav-list-item
        購入した商品-過去の取引
        %i.fa.fa-angle-right
    = link_to "" do
      %li.y__mypage-nav-list-item
        ニュース一覧
        %i.fa.fa-angle-right
    = link_to "" do
      %li.y__mypage-nav-list-item
        評価一覧
        %i.fa.fa-angle-right
    = link_to "" do
      %li.y__mypage-nav-list-item
        ガイド
        %i.fa.fa-angle-right
    = link_to "" do
      %li.y__mypage-nav-list-item
        お問い合わせ
        %i.fa.fa-angle-right
      
    %h3.y__mypage-nav-head メルペイ
    %ul.y__mypage-nav-list
      = link_to "" do
        %li.y__mypage-nav-list-item
          売上・振込申請
          %i.fa.fa-angle-right
      = link_to "" do
        %li.y__mypage-nav-list-item
          ポイント
          %i.fa.fa-angle-right
  
    %h3.y__mypage-nav-head 設定
    %ul.y__mypage-nav-list
      = link_to "" do
        %li.y__mypage-nav-list-item
          プロフィール
          %i.fa.fa-angle-right
      = link_to "" do
        %li.y__mypage-nav-list-item
          発送元お届け先住所変更
          %i.fa.fa-angle-right
      - if current_user.credit_card.present?
        = link_to credit_card_path(current_user.id) do
          %li.y__mypage-nav-list-item
            お支払い情報の確認
            %i.fa.fa-angle-right
      - else
        = link_to new_credit_card_path(current_user.id) do
          %li.y__mypage-nav-list-item
            お支払い情報の登録
            %i.fa.fa-angle-right
      = link_to "" do
        %li.y__mypage-nav-list-item
          メール/パスワード
          %i.fa.fa-angle-right
      = link_to "" do
        %li.y__mypage-nav-list-item
          本人情報
          %i.fa.fa-angle-right
      = link_to "" do
        %li.y__mypage-nav-list-item
          電話番号の確認
          %i.fa.fa-angle-right
      = link_to logout_users_path do
        %li.y__mypage-nav-list-item
          ログアウト
          %i.fa.fa-angle-right